name: FireAPI
main: fr.glowstoner.fireapi.bukkit.BukkitMain
version: 3.0.1.1 (Branche master)
author: Glowstoner
commands:
 ping:
  description: Permet de faire un test de latence !
 at:
  description: Utilise /at help pour voir la liste des commandes !
