name: FireAPI
main: fr.glowstoner.fireapi.bukkit.BukkitMain
version: 2.11.4.0
authors: Glowstoner
commands:
 ping:
  description: Permet de faire un test de latence !
 at:
  description: Utilise /at help pour voir la liste des commandes !